# Generated by Django 5.0.6 on 2024-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('suppl_id', models.AutoField(primary_key=True, serialize=False)),
                ('suppl_name', models.CharField(default='supplier', max_length=100)),
                ('suppl_email', models.EmailField(max_length=254)),
                ('suppl_addr', models.CharField(max_length=200)),
                ('suppl_site', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('suppl_img', models.ImageField(blank=True, null=True, upload_to='imgs/')),
            ],
        ),
    ]
