# Generated by Django 5.0.6 on 2024-07-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_suppl_desc_alter_supplier_suppl_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='suppl_site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
