# Generated by Django 5.0.6 on 2024-07-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_suppl_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='suppl_phone',
            field=models.CharField(max_length=12),
        ),
    ]
