# Generated by Django 5.0.6 on 2024-07-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_supplier_suppl_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='suppl_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
