# Generated by Django 5.0.6 on 2024-08-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_supplier_suppl_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='suppl_addr',
            new_name='addr',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='suppl_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='suppl_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='suppl_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='suppl_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='suppl_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='suppl_site',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='suppl_id',
        ),
        migrations.AddField(
            model_name='supplier',
            name='id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
