# Generated by Django 5.0.6 on 2024-07-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=100)),
                ('site_type', models.CharField(choices=[('Public', 'public'), ('Private', 'private'), ('Smart', 'smart'), ('Hazmat', 'hazmat'), ('Cold storage', 'cold'), ('Distribution Center', 'distribution')], max_length=50)),
                ('site_img', models.ImageField(blank=True, null=True, upload_to='imgs/')),
                ('site_addr', models.CharField(max_length=200)),
                ('site_phone', models.CharField(max_length=12)),
            ],
        ),
    ]
