# Generated by Django 5.0.6 on 2024-08-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagesites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
