# Generated by Django 5.0.6 on 2024-08-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagesites', '0002_alter_site_site_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_addr',
            new_name='addr',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_id',
        ),
        migrations.AddField(
            model_name='site',
            name='id',
            field=models.CharField(default='id000site', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
