# Generated by Django 5.0.6 on 2024-08-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagesites', '0003_rename_site_addr_site_addr_rename_site_img_site_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
