# Generated by Django 5.0.6 on 2024-08-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagesites', '0004_alter_site_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('smart', 'Smart'), ('hazmat', 'Hazmat'), ('cold', 'Cold storage'), ('distribution', 'Distribution Center')], max_length=50),
        ),
    ]
