# Generated by Django 5.0.6 on 2024-08-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagesites', '0005_alter_site_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Smart', 'Smart'), ('Hazmat', 'Hazmat'), ('Cold storage', 'Cold storage'), ('Distribution Center', 'Distribution Center')], max_length=50),
        ),
    ]
