# Generated by Django 5.0.6 on 2024-08-24 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagesites', '0006_sitetype_alter_site_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storagesites.sitetype'),
        ),
    ]
