# Generated by Django 5.0.6 on 2024-08-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='object_id',
            field=models.CharField(max_length=50),
        ),
    ]
