# Generated by Django 5.0.6 on 2024-07-10 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_rename_id_cat_product_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_title', models.CharField(max_length=100)),
                ('prod_desc', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('locat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
                ('suppl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supplier')),
            ],
        ),
    ]
