# Generated by Django 5.0.6 on 2024-07-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('main', '0002_rename_id_cat_product_cat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
