# Generated by Django 5.0.6 on 2024-07-12 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('items', '0003_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
