# Generated by Django 5.0.6 on 2024-07-13 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_suppl'),
        ('storagesites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='locat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storagesites.site'),
        ),
    ]
