# Generated by Django 5.0.6 on 2024-08-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_locat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='prod_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
