# Generated by Django 5.0.6 on 2024-08-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_prod_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='prod_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='stock',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='locat',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='prod_title',
            new_name='ttl',
        ),
        migrations.RemoveField(
            model_name='item',
            name='prod_id',
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.CharField(default='id_o0p5', max_length=50, primary_key=True, serialize=False),
        ),
    ]
