# Generated by Django 5.0.6 on 2024-08-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_rename_prod_desc_item_desc_rename_stock_item_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
