# Generated by Django 5.0.6 on 2024-08-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='item',
            name='site',
        ),
        migrations.RemoveField(
            model_name='item',
            name='suppl',
        ),
    ]
