# Generated by Django 5.0.6 on 2024-08-09 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_category_cat_name'),
        ('items', '0010_remove_item_cat_remove_item_site_remove_item_suppl'),
        ('storagesites', '0003_rename_site_addr_site_addr_rename_site_img_site_img_and_more'),
        ('suppliers', '0006_alter_supplier_suppl_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cat',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='site',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='storagesites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='suppl',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
            preserve_default=False,
        ),
    ]
