# Generated by Django 5.0.6 on 2024-08-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_item_cat_item_site_item_suppl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='suppl',
        ),
    ]
