# Generated by Django 5.0.6 on 2024-08-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_item_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
