# Generated by Django 5.0.6 on 2024-08-19 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_remove_item_prod'),
        ('products', '0003_remove_product_id_alter_product_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prod',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
