# Generated by Django 5.0.6 on 2024-08-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cat',
        ),
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('MAD', 'Moroccan Dirham'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('CHF', 'Swiss Franc')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
