# Generated by Django 5.0.6 on 2024-08-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_remove_item_cat_item_cost_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('MAD', 'Moroccan Dirham'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('CHF', 'Swiss Franc')], default='MAD', max_length=100),
        ),
    ]
