# Generated by Django 5.0.6 on 2024-08-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_item_price_alter_item_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
    ]
