# Generated by Django 5.0.6 on 2024-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_remove_item_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
