# Generated by Django 4.2.11 on 2024-06-29 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_locat', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_suppl', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('prod_title', models.CharField(max_length=100)),
                ('prod_desc', models.CharField(max_length=200)),
                ('qty_in_stock', models.IntegerField()),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('id_locat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
                ('id_suppl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supplier')),
            ],
        ),
    ]
