# Generated by Django 4.2.11 on 2024-06-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_cat',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_locat',
            new_name='locat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_suppl',
            new_name='suppl',
        ),
    ]
