# Generated by Django 5.0.6 on 2024-07-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_id_cat_product_cat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
