# Generated by Django 5.0.6 on 2024-07-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='def_cat', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='def_locat', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='def_suppl', max_length=100),
        ),
    ]
