# Generated by Django 5.0.6 on 2024-07-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_suppl'),
        ('main', '0005_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
