# Generated by Django 5.0.6 on 2024-07-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='def_cat', max_length=100)),
            ],
        ),
    ]
