# Generated by Django 5.0.6 on 2024-07-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id_cat',
            new_name='cat_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_clr',
            field=models.CharField(default='gray', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_desc',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_name',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
