# Generated by Django 5.0.6 on 2024-07-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_id_cat_category_cat_id_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_clr',
            field=models.CharField(choices=[('R', 'red'), ('G', 'green'), ('B', 'blue')], default='G', max_length=20),
        ),
    ]
