# Generated by Django 5.0.6 on 2024-07-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_cat_clr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_clr',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue')], default='G', max_length=20),
        ),
    ]
