# Generated by Django 5.0.6 on 2024-07-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_cat_clr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_clr',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('slate', 'Slate'), ('blue', 'Blue'), ('gray', 'gray'), ('orange', 'Orange'), ('amber', 'Amber'), ('yellow', 'Yellow'), ('lime', 'Lime'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('cyan', 'Cyan'), ('sky', 'Sky'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('purple', 'Purple'), ('pink', 'Pink'), ('rose', 'Rose')], max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=100),
        ),
    ]
