# Generated by Django 5.0.6 on 2024-07-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_cat_clr_alter_category_cat_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
