# Generated by Django 5.0.6 on 2024-08-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_category_cat_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_clr',
            new_name='clr',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
