# Generated by Django 5.0.6 on 2024-08-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ttl', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='imgs/')),
            ],
        ),
    ]
