# Generated by Django 5.0.6 on 2024-08-19 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_id_alter_product_art'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='art',
            new_name='id',
        ),
    ]
